// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/tunnel/tunnel.proto

package tunnel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TunnelHub_AgentStream_FullMethodName = "/tunnel.TunnelHub/AgentStream"
)

// TunnelHubClient is the client API for TunnelHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TunnelHubClient interface {
	AgentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error)
}

type tunnelHubClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelHubClient(cc grpc.ClientConnInterface) TunnelHubClient {
	return &tunnelHubClient{cc}
}

func (c *tunnelHubClient) AgentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TunnelHub_ServiceDesc.Streams[0], TunnelHub_AgentStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelHub_AgentStreamClient = grpc.BidiStreamingClient[AgentMessage, ServerMessage]

// TunnelHubServer is the server API for TunnelHub service.
// All implementations must embed UnimplementedTunnelHubServer
// for forward compatibility.
type TunnelHubServer interface {
	AgentStream(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error
	mustEmbedUnimplementedTunnelHubServer()
}

// UnimplementedTunnelHubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTunnelHubServer struct{}

func (UnimplementedTunnelHubServer) AgentStream(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method AgentStream not implemented")
}
func (UnimplementedTunnelHubServer) mustEmbedUnimplementedTunnelHubServer() {}
func (UnimplementedTunnelHubServer) testEmbeddedByValue()                   {}

// UnsafeTunnelHubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelHubServer will
// result in compilation errors.
type UnsafeTunnelHubServer interface {
	mustEmbedUnimplementedTunnelHubServer()
}

func RegisterTunnelHubServer(s grpc.ServiceRegistrar, srv TunnelHubServer) {
	// If the following call panics, it indicates UnimplementedTunnelHubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TunnelHub_ServiceDesc, srv)
}

func _TunnelHub_AgentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelHubServer).AgentStream(&grpc.GenericServerStream[AgentMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelHub_AgentStreamServer = grpc.BidiStreamingServer[AgentMessage, ServerMessage]

// TunnelHub_ServiceDesc is the grpc.ServiceDesc for TunnelHub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TunnelHub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.TunnelHub",
	HandlerType: (*TunnelHubServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AgentStream",
			Handler:       _TunnelHub_AgentStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/tunnel/tunnel.proto",
}
