// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/tunnel/tunnel.proto

package tunnel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_TaskResult
	//	*AgentMessage_Join
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_tunnel_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *HeartbeatMsg {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetTaskResult() *TaskResultMsg {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *AgentMessage) GetJoin() *JoinMsg {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Join); ok {
			return x.Join
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *HeartbeatMsg `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_TaskResult struct {
	TaskResult *TaskResultMsg `protobuf:"bytes,2,opt,name=task_result,json=taskResult,proto3,oneof"`
}

type AgentMessage_Join struct {
	Join *JoinMsg `protobuf:"bytes,3,opt,name=join,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_TaskResult) isAgentMessage_Payload() {}

func (*AgentMessage_Join) isAgentMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Task
	//	*ServerMessage_Ping
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_tunnel_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetTask() *TaskMsg {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *ServerMessage) GetPing() *PingMsg {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Task struct {
	Task *TaskMsg `protobuf:"bytes,1,opt,name=task,proto3,oneof"`
}

type ServerMessage_Ping struct {
	Ping *PingMsg `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

func (*ServerMessage_Task) isServerMessage_Payload() {}

func (*ServerMessage_Ping) isServerMessage_Payload() {}

type JoinMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	TunnelIp      string                 `protobuf:"bytes,3,opt,name=tunnel_ip,json=tunnelIp,proto3" json:"tunnel_ip,omitempty"`
	TokenHash     string                 `protobuf:"bytes,4,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinMsg) Reset() {
	*x = JoinMsg{}
	mi := &file_proto_tunnel_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMsg) ProtoMessage() {}

func (x *JoinMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMsg.ProtoReflect.Descriptor instead.
func (*JoinMsg) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *JoinMsg) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinMsg) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *JoinMsg) GetTunnelIp() string {
	if x != nil {
		return x.TunnelIp
	}
	return ""
}

func (x *JoinMsg) GetTokenHash() string {
	if x != nil {
		return x.TokenHash
	}
	return ""
}

type HeartbeatMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnix int64                  `protobuf:"varint,1,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	VcpusFree     int32                  `protobuf:"varint,2,opt,name=vcpus_free,json=vcpusFree,proto3" json:"vcpus_free,omitempty"`
	MemoryFreeMb  int64                  `protobuf:"varint,3,opt,name=memory_free_mb,json=memoryFreeMb,proto3" json:"memory_free_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMsg) Reset() {
	*x = HeartbeatMsg{}
	mi := &file_proto_tunnel_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMsg) ProtoMessage() {}

func (x *HeartbeatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMsg.ProtoReflect.Descriptor instead.
func (*HeartbeatMsg) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatMsg) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *HeartbeatMsg) GetVcpusFree() int32 {
	if x != nil {
		return x.VcpusFree
	}
	return 0
}

func (x *HeartbeatMsg) GetMemoryFreeMb() int64 {
	if x != nil {
		return x.MemoryFreeMb
	}
	return 0
}

type TaskMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType      string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMsg) Reset() {
	*x = TaskMsg{}
	mi := &file_proto_tunnel_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMsg) ProtoMessage() {}

func (x *TaskMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMsg.ProtoReflect.Descriptor instead.
func (*TaskMsg) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *TaskMsg) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskMsg) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *TaskMsg) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TaskResultMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Result        []byte                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultMsg) Reset() {
	*x = TaskResultMsg{}
	mi := &file_proto_tunnel_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultMsg) ProtoMessage() {}

func (x *TaskResultMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultMsg.ProtoReflect.Descriptor instead.
func (*TaskResultMsg) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *TaskResultMsg) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResultMsg) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResultMsg) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResultMsg) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type PingMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingMsg) Reset() {
	*x = PingMsg{}
	mi := &file_proto_tunnel_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMsg) ProtoMessage() {}

func (x *PingMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMsg.ProtoReflect.Descriptor instead.
func (*PingMsg) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_tunnel_proto_rawDescGZIP(), []int{6}
}

var File_proto_tunnel_tunnel_proto protoreflect.FileDescriptor

const file_proto_tunnel_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x19proto/tunnel/tunnel.proto\x12\x06tunnel\"\xb0\x01\n" +
	"\fAgentMessage\x124\n" +
	"\theartbeat\x18\x01 \x01(\v2\x14.tunnel.HeartbeatMsgH\x00R\theartbeat\x128\n" +
	"\vtask_result\x18\x02 \x01(\v2\x15.tunnel.TaskResultMsgH\x00R\n" +
	"taskResult\x12%\n" +
	"\x04join\x18\x03 \x01(\v2\x0f.tunnel.JoinMsgH\x00R\x04joinB\t\n" +
	"\apayload\"h\n" +
	"\rServerMessage\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.tunnel.TaskMsgH\x00R\x04task\x12%\n" +
	"\x04ping\x18\x02 \x01(\v2\x0f.tunnel.PingMsgH\x00R\x04pingB\t\n" +
	"\apayload\"z\n" +
	"\aJoinMsg\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1b\n" +
	"\ttunnel_ip\x18\x03 \x01(\tR\btunnelIp\x12\x1d\n" +
	"\n" +
	"token_hash\x18\x04 \x01(\tR\ttokenHash\"z\n" +
	"\fHeartbeatMsg\x12%\n" +
	"\x0etimestamp_unix\x18\x01 \x01(\x03R\rtimestampUnix\x12\x1d\n" +
	"\n" +
	"vcpus_free\x18\x02 \x01(\x05R\tvcpusFree\x12$\n" +
	"\x0ememory_free_mb\x18\x03 \x01(\x03R\fmemoryFreeMb\"Y\n" +
	"\aTaskMsg\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"p\n" +
	"\rTaskResultMsg\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x16\n" +
	"\x06result\x18\x04 \x01(\fR\x06result\"\t\n" +
	"\aPingMsg2M\n" +
	"\tTunnelHub\x12@\n" +
	"\vAgentStream\x12\x14.tunnel.AgentMessage\x1a\x15.tunnel.ServerMessage\"\x00(\x010\x01B,Z*github.com/cobaltcore-dev/o3k/proto/tunnelb\x06proto3"

var (
	file_proto_tunnel_tunnel_proto_rawDescOnce sync.Once
	file_proto_tunnel_tunnel_proto_rawDescData []byte
)

func file_proto_tunnel_tunnel_proto_rawDescGZIP() []byte {
	file_proto_tunnel_tunnel_proto_rawDescOnce.Do(func() {
		file_proto_tunnel_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tunnel_tunnel_proto_rawDesc), len(file_proto_tunnel_tunnel_proto_rawDesc)))
	})
	return file_proto_tunnel_tunnel_proto_rawDescData
}

var file_proto_tunnel_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_tunnel_tunnel_proto_goTypes = []any{
	(*AgentMessage)(nil),  // 0: tunnel.AgentMessage
	(*ServerMessage)(nil), // 1: tunnel.ServerMessage
	(*JoinMsg)(nil),       // 2: tunnel.JoinMsg
	(*HeartbeatMsg)(nil),  // 3: tunnel.HeartbeatMsg
	(*TaskMsg)(nil),       // 4: tunnel.TaskMsg
	(*TaskResultMsg)(nil), // 5: tunnel.TaskResultMsg
	(*PingMsg)(nil),       // 6: tunnel.PingMsg
}
var file_proto_tunnel_tunnel_proto_depIdxs = []int32{
	3, // 0: tunnel.AgentMessage.heartbeat:type_name -> tunnel.HeartbeatMsg
	5, // 1: tunnel.AgentMessage.task_result:type_name -> tunnel.TaskResultMsg
	2, // 2: tunnel.AgentMessage.join:type_name -> tunnel.JoinMsg
	4, // 3: tunnel.ServerMessage.task:type_name -> tunnel.TaskMsg
	6, // 4: tunnel.ServerMessage.ping:type_name -> tunnel.PingMsg
	0, // 5: tunnel.TunnelHub.AgentStream:input_type -> tunnel.AgentMessage
	1, // 6: tunnel.TunnelHub.AgentStream:output_type -> tunnel.ServerMessage
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_tunnel_tunnel_proto_init() }
func file_proto_tunnel_tunnel_proto_init() {
	if File_proto_tunnel_tunnel_proto != nil {
		return
	}
	file_proto_tunnel_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_TaskResult)(nil),
		(*AgentMessage_Join)(nil),
	}
	file_proto_tunnel_tunnel_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Task)(nil),
		(*ServerMessage_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tunnel_tunnel_proto_rawDesc), len(file_proto_tunnel_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tunnel_tunnel_proto_goTypes,
		DependencyIndexes: file_proto_tunnel_tunnel_proto_depIdxs,
		MessageInfos:      file_proto_tunnel_tunnel_proto_msgTypes,
	}.Build()
	File_proto_tunnel_tunnel_proto = out.File
	file_proto_tunnel_tunnel_proto_goTypes = nil
	file_proto_tunnel_tunnel_proto_depIdxs = nil
}
