ALTER TABLE compute_nodes ADD COLUMN IF NOT EXISTS total_vcpu INT NOT NULL DEFAULT 0;
ALTER TABLE compute_nodes ADD COLUMN IF NOT EXISTS total_ram_mb BIGINT NOT NULL DEFAULT 0;
ALTER TABLE compute_nodes ADD COLUMN IF NOT EXISTS total_disk_gb BIGINT NOT NULL DEFAULT 0;
ALTER TABLE compute_nodes ADD COLUMN IF NOT EXISTS reserved_vcpu INT NOT NULL DEFAULT 0;
ALTER TABLE compute_nodes ADD COLUMN IF NOT EXISTS reserved_ram_mb BIGINT NOT NULL DEFAULT 0;
ALTER TABLE compute_nodes ADD COLUMN IF NOT EXISTS reserved_disk_gb BIGINT NOT NULL DEFAULT 0;
ALTER TABLE compute_nodes ADD COLUMN IF NOT EXISTS stats_updated_at TIMESTAMPTZ;
ALTER TABLE compute_nodes ADD COLUMN IF NOT EXISTS agent_stream_server_id TEXT;
