ALTER TABLE compute_nodes ADD COLUMN IF NOT EXISTS total_vcpu INTEGER NOT NULL DEFAULT 0;
ALTER TABLE compute_nodes ADD COLUMN IF NOT EXISTS total_ram_mb INTEGER NOT NULL DEFAULT 0;
ALTER TABLE compute_nodes ADD COLUMN IF NOT EXISTS total_disk_gb INTEGER NOT NULL DEFAULT 0;
ALTER TABLE compute_nodes ADD COLUMN IF NOT EXISTS reserved_vcpu INTEGER NOT NULL DEFAULT 0;
ALTER TABLE compute_nodes ADD COLUMN IF NOT EXISTS reserved_ram_mb INTEGER NOT NULL DEFAULT 0;
ALTER TABLE compute_nodes ADD COLUMN IF NOT EXISTS reserved_disk_gb INTEGER NOT NULL DEFAULT 0;
ALTER TABLE compute_nodes ADD COLUMN IF NOT EXISTS stats_updated_at TEXT;
ALTER TABLE compute_nodes ADD COLUMN IF NOT EXISTS agent_stream_server_id TEXT;
